/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Nodes controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, AppNodeRunDto, NodesPageDto } from "../models";

@Injectable({ providedIn: "root" })
export class NodesService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    listNodes(mainAppId?: string | null, afterRecordTime?: string | null, appBuildIds?: Array<unknown> | null, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<AppNodeRunDto>>;
    listNodes(mainAppId?: string | null, afterRecordTime?: string | null, appBuildIds?: Array<unknown> | null, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<AppNodeRunDto>>>;
    listNodes(mainAppId?: string | null, afterRecordTime?: string | null, appBuildIds?: Array<unknown> | null, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<AppNodeRunDto>>>;
    listNodes(mainAppId?: string | null, afterRecordTime?: string | null, appBuildIds?: Array<unknown> | null, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/nodes`;

        let params = new HttpParams();
        if (mainAppId != null) {
            params = HttpParamsBuilder.addToHttpParams(params, mainAppId, 'main_app_id');
        }
        if (afterRecordTime != null) {
            params = HttpParamsBuilder.addToHttpParams(params, afterRecordTime, 'after_record_time');
        }
        if (appBuildIds != null) {
            params = HttpParamsBuilder.addToHttpParams(params, appBuildIds, 'app_build_ids');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Add default headers if not already present
        if (!headers.has('X-Requested-With')) {
            headers = headers.set('X-Requested-With', 'XMLHttpRequest');
        }
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    nodesPage(afterRecordTime?: string | null, appBuildIds?: Array<unknown> | null, observe?: 'body', options?: RequestOptions<'json'>): Observable<NodesPageDto>;
    nodesPage(afterRecordTime?: string | null, appBuildIds?: Array<unknown> | null, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<NodesPageDto>>;
    nodesPage(afterRecordTime?: string | null, appBuildIds?: Array<unknown> | null, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<NodesPageDto>>;
    nodesPage(afterRecordTime?: string | null, appBuildIds?: Array<unknown> | null, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/nodes/page`;

        let params = new HttpParams();
        if (afterRecordTime != null) {
            params = HttpParamsBuilder.addToHttpParams(params, afterRecordTime, 'after_record_time');
        }
        if (appBuildIds != null) {
            params = HttpParamsBuilder.addToHttpParams(params, appBuildIds, 'app_build_ids');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Add default headers if not already present
        if (!headers.has('X-Requested-With')) {
            headers = headers.set('X-Requested-With', 'XMLHttpRequest');
        }
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
