/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated Angular service for Records controller
* Do not edit this file manually
*/
import { HttpClient, HttpContext, HttpContextToken, HttpEvent, HttpHeaders, HttpParams, HttpResponse } from "@angular/common/http";
import { inject, Injectable } from "@angular/core";
import { Observable } from "rxjs";
import { BASE_PATH_DEFAULT, CLIENT_CONTEXT_TOKEN_DEFAULT } from "../tokens";
import { HttpParamsBuilder } from "../utils/http-params-builder";
import { RequestOptions, TracingRecordDto, TracingTreeRecordDto } from "../models";

@Injectable({ providedIn: "root" })
export class RecordsService {
    private readonly httpClient: HttpClient = inject(HttpClient);
    private readonly basePath: string = inject(BASE_PATH_DEFAULT);
    private readonly clientContextToken: HttpContextToken<string> = CLIENT_CONTEXT_TOKEN_DEFAULT;

    private createContextWithClientId(existingContext?: HttpContext): HttpContext {
        const context = existingContext || new HttpContext();
        return context.set(this.clientContextToken, 'default');
    }

    listRecords(cursor?: any, count?: number | null, search?: string | null, scene?: any, appBuildIds?: Array<unknown> | null, appRunIds?: Array<unknown> | null, nodeIds?: Array<unknown> | null, parentId?: string | null, parentSpanTIds?: Array<unknown> | null, startTime?: string | null, endTime?: string | null, kinds?: Array<unknown> | null, spanIds?: Array<unknown> | null, targets?: Array<unknown> | null, name?: Array<unknown> | null, fields?: Array<unknown> | null, levels?: Array<unknown> | null, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<TracingRecordDto>>;
    listRecords(cursor?: any, count?: number | null, search?: string | null, scene?: any, appBuildIds?: Array<unknown> | null, appRunIds?: Array<unknown> | null, nodeIds?: Array<unknown> | null, parentId?: string | null, parentSpanTIds?: Array<unknown> | null, startTime?: string | null, endTime?: string | null, kinds?: Array<unknown> | null, spanIds?: Array<unknown> | null, targets?: Array<unknown> | null, name?: Array<unknown> | null, fields?: Array<unknown> | null, levels?: Array<unknown> | null, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<TracingRecordDto>>>;
    listRecords(cursor?: any, count?: number | null, search?: string | null, scene?: any, appBuildIds?: Array<unknown> | null, appRunIds?: Array<unknown> | null, nodeIds?: Array<unknown> | null, parentId?: string | null, parentSpanTIds?: Array<unknown> | null, startTime?: string | null, endTime?: string | null, kinds?: Array<unknown> | null, spanIds?: Array<unknown> | null, targets?: Array<unknown> | null, name?: Array<unknown> | null, fields?: Array<unknown> | null, levels?: Array<unknown> | null, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<TracingRecordDto>>>;
    listRecords(cursor?: any, count?: number | null, search?: string | null, scene?: any, appBuildIds?: Array<unknown> | null, appRunIds?: Array<unknown> | null, nodeIds?: Array<unknown> | null, parentId?: string | null, parentSpanTIds?: Array<unknown> | null, startTime?: string | null, endTime?: string | null, kinds?: Array<unknown> | null, spanIds?: Array<unknown> | null, targets?: Array<unknown> | null, name?: Array<unknown> | null, fields?: Array<unknown> | null, levels?: Array<unknown> | null, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/records`;

        let params = new HttpParams();
        if (cursor != null) {
            params = HttpParamsBuilder.addToHttpParams(params, cursor, 'cursor');
        }
        if (count != null) {
            params = HttpParamsBuilder.addToHttpParams(params, count, 'count');
        }
        if (search != null) {
            params = HttpParamsBuilder.addToHttpParams(params, search, 'search');
        }
        if (scene != null) {
            params = HttpParamsBuilder.addToHttpParams(params, scene, 'scene');
        }
        if (appBuildIds != null) {
            params = HttpParamsBuilder.addToHttpParams(params, appBuildIds, 'app_build_ids');
        }
        if (appRunIds != null) {
            params = HttpParamsBuilder.addToHttpParams(params, appRunIds, 'app_run_ids');
        }
        if (nodeIds != null) {
            params = HttpParamsBuilder.addToHttpParams(params, nodeIds, 'node_ids');
        }
        if (parentId != null) {
            params = HttpParamsBuilder.addToHttpParams(params, parentId, 'parent_id');
        }
        if (parentSpanTIds != null) {
            params = HttpParamsBuilder.addToHttpParams(params, parentSpanTIds, 'parent_span_t_ids');
        }
        if (startTime != null) {
            params = HttpParamsBuilder.addToHttpParams(params, startTime, 'start_time');
        }
        if (endTime != null) {
            params = HttpParamsBuilder.addToHttpParams(params, endTime, 'end_time');
        }
        if (kinds != null) {
            params = HttpParamsBuilder.addToHttpParams(params, kinds, 'kinds');
        }
        if (spanIds != null) {
            params = HttpParamsBuilder.addToHttpParams(params, spanIds, 'span_ids');
        }
        if (targets != null) {
            params = HttpParamsBuilder.addToHttpParams(params, targets, 'targets');
        }
        if (name != null) {
            params = HttpParamsBuilder.addToHttpParams(params, name, 'name');
        }
        if (fields != null) {
            params = HttpParamsBuilder.addToHttpParams(params, fields, 'fields');
        }
        if (levels != null) {
            params = HttpParamsBuilder.addToHttpParams(params, levels, 'levels');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Add default headers if not already present
        if (!headers.has('X-Requested-With')) {
            headers = headers.set('X-Requested-With', 'XMLHttpRequest');
        }
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    listTreeRecords(cursor?: any, count?: number | null, search?: string | null, scene?: any, appBuildIds?: Array<unknown> | null, appRunIds?: Array<unknown> | null, nodeIds?: Array<unknown> | null, parentId?: string | null, parentSpanTIds?: Array<unknown> | null, startTime?: string | null, endTime?: string | null, kinds?: Array<unknown> | null, spanIds?: Array<unknown> | null, targets?: Array<unknown> | null, name?: Array<unknown> | null, fields?: Array<unknown> | null, levels?: Array<unknown> | null, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<TracingTreeRecordDto>>;
    listTreeRecords(cursor?: any, count?: number | null, search?: string | null, scene?: any, appBuildIds?: Array<unknown> | null, appRunIds?: Array<unknown> | null, nodeIds?: Array<unknown> | null, parentId?: string | null, parentSpanTIds?: Array<unknown> | null, startTime?: string | null, endTime?: string | null, kinds?: Array<unknown> | null, spanIds?: Array<unknown> | null, targets?: Array<unknown> | null, name?: Array<unknown> | null, fields?: Array<unknown> | null, levels?: Array<unknown> | null, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<TracingTreeRecordDto>>>;
    listTreeRecords(cursor?: any, count?: number | null, search?: string | null, scene?: any, appBuildIds?: Array<unknown> | null, appRunIds?: Array<unknown> | null, nodeIds?: Array<unknown> | null, parentId?: string | null, parentSpanTIds?: Array<unknown> | null, startTime?: string | null, endTime?: string | null, kinds?: Array<unknown> | null, spanIds?: Array<unknown> | null, targets?: Array<unknown> | null, name?: Array<unknown> | null, fields?: Array<unknown> | null, levels?: Array<unknown> | null, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<TracingTreeRecordDto>>>;
    listTreeRecords(cursor?: any, count?: number | null, search?: string | null, scene?: any, appBuildIds?: Array<unknown> | null, appRunIds?: Array<unknown> | null, nodeIds?: Array<unknown> | null, parentId?: string | null, parentSpanTIds?: Array<unknown> | null, startTime?: string | null, endTime?: string | null, kinds?: Array<unknown> | null, spanIds?: Array<unknown> | null, targets?: Array<unknown> | null, name?: Array<unknown> | null, fields?: Array<unknown> | null, levels?: Array<unknown> | null, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/records/tree`;

        let params = new HttpParams();
        if (cursor != null) {
            params = HttpParamsBuilder.addToHttpParams(params, cursor, 'cursor');
        }
        if (count != null) {
            params = HttpParamsBuilder.addToHttpParams(params, count, 'count');
        }
        if (search != null) {
            params = HttpParamsBuilder.addToHttpParams(params, search, 'search');
        }
        if (scene != null) {
            params = HttpParamsBuilder.addToHttpParams(params, scene, 'scene');
        }
        if (appBuildIds != null) {
            params = HttpParamsBuilder.addToHttpParams(params, appBuildIds, 'app_build_ids');
        }
        if (appRunIds != null) {
            params = HttpParamsBuilder.addToHttpParams(params, appRunIds, 'app_run_ids');
        }
        if (nodeIds != null) {
            params = HttpParamsBuilder.addToHttpParams(params, nodeIds, 'node_ids');
        }
        if (parentId != null) {
            params = HttpParamsBuilder.addToHttpParams(params, parentId, 'parent_id');
        }
        if (parentSpanTIds != null) {
            params = HttpParamsBuilder.addToHttpParams(params, parentSpanTIds, 'parent_span_t_ids');
        }
        if (startTime != null) {
            params = HttpParamsBuilder.addToHttpParams(params, startTime, 'start_time');
        }
        if (endTime != null) {
            params = HttpParamsBuilder.addToHttpParams(params, endTime, 'end_time');
        }
        if (kinds != null) {
            params = HttpParamsBuilder.addToHttpParams(params, kinds, 'kinds');
        }
        if (spanIds != null) {
            params = HttpParamsBuilder.addToHttpParams(params, spanIds, 'span_ids');
        }
        if (targets != null) {
            params = HttpParamsBuilder.addToHttpParams(params, targets, 'targets');
        }
        if (name != null) {
            params = HttpParamsBuilder.addToHttpParams(params, name, 'name');
        }
        if (fields != null) {
            params = HttpParamsBuilder.addToHttpParams(params, fields, 'fields');
        }
        if (levels != null) {
            params = HttpParamsBuilder.addToHttpParams(params, levels, 'levels');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Add default headers if not already present
        if (!headers.has('X-Requested-With')) {
            headers = headers.set('X-Requested-With', 'XMLHttpRequest');
        }
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }

    listTreeRecordsByIds(ids: Array<number>, observe?: 'body', options?: RequestOptions<'json'>): Observable<Array<TracingTreeRecordDto>>;
    listTreeRecordsByIds(ids: Array<number>, observe?: 'response', options?: RequestOptions<'json'>): Observable<HttpResponse<Array<TracingTreeRecordDto>>>;
    listTreeRecordsByIds(ids: Array<number>, observe?: 'events', options?: RequestOptions<'json'>): Observable<HttpEvent<Array<TracingTreeRecordDto>>>;
    listTreeRecordsByIds(ids: Array<number>, observe?: 'body' | 'events' | 'response', options?: RequestOptions<'arraybuffer' | 'blob' | 'json' | 'text'>): Observable<any> {
        const url = `${this.basePath}/api/records/tree_by_ids`;

        let params = new HttpParams();
        if (ids != null) {
            params = HttpParamsBuilder.addToHttpParams(params, ids, 'ids');
        }

        let headers: HttpHeaders;
        if (options?.headers instanceof HttpHeaders) {
            headers = options.headers;
        } else {
            headers = new HttpHeaders(options?.headers);
        }
        // Add default headers if not already present
        if (!headers.has('X-Requested-With')) {
            headers = headers.set('X-Requested-With', 'XMLHttpRequest');
        }
        if (!headers.has('Accept')) {
            headers = headers.set('Accept', 'application/json');
        }

        const requestOptions: any = {
            observe: observe as any,
            headers,
            params,
            reportProgress: options?.reportProgress,
            withCredentials: options?.withCredentials,
            context: this.createContextWithClientId(options?.context)
        };

        return this.httpClient.get(url, requestOptions);
    }
}
