// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppLatestRunInfoDto } from "./AppLatestRunInfoDto";
import type { JsonValue } from "./serde_json/JsonValue";

export type AppLatestInfoDto = { id: string, name: string, version: string, static_data: JsonValue | null, build_time: string, run_info: AppLatestRunInfoDto | null, };
