// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type TracingRecordDto = { app_id: string, app_version: string, app_run_id: string, name: string, kind: string, level: number | null, span_id: string | null, fields: JsonValue | null, target: string | null, module_path: string | null, position_info: string | null, record_time: string, creation_time: string, span_id_is_stable: boolean, parent_span_id: string | null, tracing_span_id: bigint | null, parent_tracing_span_id: bigint | null, };
