//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tracing_record")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub app_run_record_index: i64,
    pub app_id: Uuid,
    pub app_version: String,
    pub app_run_id: Uuid,
    pub node_id: String,
    #[sea_orm(column_type = "Text")]
    pub name: String,
    pub record_time: DateTimeWithTimeZone,
    pub kind: String,
    pub creation_time: DateTimeWithTimeZone,
    pub level: Option<i32>,
    pub span_id: Option<Uuid>,
    pub parent_span_t_id: Option<i64>,
    pub parent_id: Option<Uuid>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub fields: Option<Json>,
    pub target: Option<String>,
    pub module_path: Option<String>,
    pub position_info: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
