//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "tracing_span_run")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub app_run_id: Uuid,
    pub span_id: Uuid,
    pub run_time: DateTimeWithTimeZone,
    #[sea_orm(column_type = "Double", nullable)]
    pub busy_duration: Option<f64>,
    #[sea_orm(column_type = "Double", nullable)]
    pub idle_duration: Option<f64>,
    pub record_id: i64,
    pub close_record_id: Option<i64>,
    pub exception_end: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub fields: Option<Json>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::app_run::Entity",
        from = "Column::AppRunId",
        to = "super::app_run::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AppRun,
    #[sea_orm(
        belongs_to = "super::tracing_span::Entity",
        from = "Column::SpanId",
        to = "super::tracing_span::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TracingSpan,
}

impl Related<super::app_run::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppRun.def()
    }
}

impl Related<super::tracing_span::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TracingSpan.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
