/* tslint:disable */
/* eslint-disable */
/**
 * tracing-lv-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CursorInfo
 */
export interface CursorInfo {
    /**
     * 
     * @type {number}
     * @memberof CursorInfo
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof CursorInfo
     */
    isBefore: boolean;
}

/**
 * Check if a given object implements the CursorInfo interface.
 */
export function instanceOfCursorInfo(value: object): value is CursorInfo {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isBefore' in value) || value['isBefore'] === undefined) return false;
    return true;
}

export function CursorInfoFromJSON(json: any): CursorInfo {
    return CursorInfoFromJSONTyped(json, false);
}

export function CursorInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CursorInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'isBefore': json['is_before'],
    };
}

  export function CursorInfoToJSON(json: any): CursorInfo {
      return CursorInfoToJSONTyped(json, false);
  }

  export function CursorInfoToJSONTyped(value?: CursorInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'is_before': value['isBefore'],
    };
}

