/* tslint:disable */
/* eslint-disable */
/**
 * tracing-lv-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ListRecordsSpanTIdParameter
 * 
 * @export
 */
export type ListRecordsSpanTIdParameter = number;

export function ListRecordsSpanTIdParameterFromJSON(json: any): ListRecordsSpanTIdParameter {
    return ListRecordsSpanTIdParameterFromJSONTyped(json, false);
}

export function ListRecordsSpanTIdParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListRecordsSpanTIdParameter {
    if (json == null) {
        return json;
    }
    if (instanceOfnumber(json)) {
        return numberFromJSONTyped(json, true);
    }

    return {} as any;
}

export function ListRecordsSpanTIdParameterToJSON(value?: ListRecordsSpanTIdParameter | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfnumber(value)) {
        return numberToJSON(value as number);
    }

    return {};
}

