/* tslint:disable */
/* eslint-disable */
/**
 * tracing-lv-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppNodeRunDto } from './AppNodeRunDto';
import {
    AppNodeRunDtoFromJSON,
    AppNodeRunDtoFromJSONTyped,
    AppNodeRunDtoToJSON,
    AppNodeRunDtoToJSONTyped,
} from './AppNodeRunDto';

/**
 * 
 * @export
 * @interface NodePageEventOneOf2
 */
export interface NodePageEventOneOf2 {
    /**
     * 
     * @type {AppNodeRunDto}
     * @memberof NodePageEventOneOf2
     */
    nodeAppStop: AppNodeRunDto;
}

/**
 * Check if a given object implements the NodePageEventOneOf2 interface.
 */
export function instanceOfNodePageEventOneOf2(value: object): value is NodePageEventOneOf2 {
    if (!('nodeAppStop' in value) || value['nodeAppStop'] === undefined) return false;
    return true;
}

export function NodePageEventOneOf2FromJSON(json: any): NodePageEventOneOf2 {
    return NodePageEventOneOf2FromJSONTyped(json, false);
}

export function NodePageEventOneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): NodePageEventOneOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'nodeAppStop': AppNodeRunDtoFromJSON(json['NodeAppStop']),
    };
}

  export function NodePageEventOneOf2ToJSON(json: any): NodePageEventOneOf2 {
      return NodePageEventOneOf2ToJSONTyped(json, false);
  }

  export function NodePageEventOneOf2ToJSONTyped(value?: NodePageEventOneOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'NodeAppStop': AppNodeRunDtoToJSON(value['nodeAppStop']),
    };
}

