/* tslint:disable */
/* eslint-disable */
/**
 * tracing-lv-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { NodePageEventOneOf } from './NodePageEventOneOf';
import {
    instanceOfNodePageEventOneOf,
    NodePageEventOneOfFromJSON,
    NodePageEventOneOfFromJSONTyped,
    NodePageEventOneOfToJSON,
} from './NodePageEventOneOf';
import type { NodePageEventOneOf1 } from './NodePageEventOneOf1';
import {
    instanceOfNodePageEventOneOf1,
    NodePageEventOneOf1FromJSON,
    NodePageEventOneOf1FromJSONTyped,
    NodePageEventOneOf1ToJSON,
} from './NodePageEventOneOf1';
import type { NodePageEventOneOf2 } from './NodePageEventOneOf2';
import {
    instanceOfNodePageEventOneOf2,
    NodePageEventOneOf2FromJSON,
    NodePageEventOneOf2FromJSONTyped,
    NodePageEventOneOf2ToJSON,
} from './NodePageEventOneOf2';

/**
 * @type NodePageEvent
 * 
 * @export
 */
export type NodePageEvent = NodePageEventOneOf | NodePageEventOneOf1 | NodePageEventOneOf2;

export function NodePageEventFromJSON(json: any): NodePageEvent {
    return NodePageEventFromJSONTyped(json, false);
}

export function NodePageEventFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodePageEvent {
    if (json == null) {
        return json;
    }
    if (instanceOfNodePageEventOneOf(json)) {
        return NodePageEventOneOfFromJSONTyped(json, true);
    }
    if (instanceOfNodePageEventOneOf1(json)) {
        return NodePageEventOneOf1FromJSONTyped(json, true);
    }
    if (instanceOfNodePageEventOneOf2(json)) {
        return NodePageEventOneOf2FromJSONTyped(json, true);
    }

    return {} as any;
}

export function NodePageEventToJSON(value?: NodePageEvent | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfNodePageEventOneOf(value)) {
        return NodePageEventOneOfToJSON(value as NodePageEventOneOf);
    }
    if (instanceOfNodePageEventOneOf1(value)) {
        return NodePageEventOneOf1ToJSON(value as NodePageEventOneOf1);
    }
    if (instanceOfNodePageEventOneOf2(value)) {
        return NodePageEventOneOf2ToJSON(value as NodePageEventOneOf2);
    }

    return {};
}

