/* tslint:disable */
/* eslint-disable */
/**
 * tracing_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {mapValues} from '../runtime';

/**
 *
 * @export
 * @interface NodePageEventOneOf1NodeAppStart
 */
export interface NodePageEventOneOf1NodeAppStart {
  /**
   *
   * @type {string}
   * @memberof NodePageEventOneOf1NodeAppStart
   */
  nodeId: string;
  /**
   *
   * @type {Date}
   * @memberof NodePageEventOneOf1NodeAppStart
   */
  startDate: Date;
}

/**
 * Check if a given object implements the NodePageEventOneOf1NodeAppStart interface.
 */
export function instanceOfNodePageEventOneOf1NodeAppStart(value: object): value is NodePageEventOneOf1NodeAppStart {
  if (!('nodeId' in value) || value['nodeId'] === undefined) return false;
  if (!('startDate' in value) || value['startDate'] === undefined) return false;
  return true;
}

export function NodePageEventOneOf1NodeAppStartFromJSON(json: any): NodePageEventOneOf1NodeAppStart {
  return NodePageEventOneOf1NodeAppStartFromJSONTyped(json, false);
}

export function NodePageEventOneOf1NodeAppStartFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodePageEventOneOf1NodeAppStart {
  if (json == null) {
    return json;
  }
  return {

    'nodeId': json['node_id'],
    'startDate': (new Date(json['start_date'])),
  };
}

export function NodePageEventOneOf1NodeAppStartToJSON(json: any): NodePageEventOneOf1NodeAppStart {
  return NodePageEventOneOf1NodeAppStartToJSONTyped(json, false);
}

export function NodePageEventOneOf1NodeAppStartToJSONTyped(value?: NodePageEventOneOf1NodeAppStart | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'node_id': value['nodeId'],
    'start_date': ((value['startDate']).toISOString()),
  };
}

