/* tslint:disable */
/* eslint-disable */
/**
 * tracing_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {mapValues} from '../runtime';

/**
 *
 * @export
 * @interface NodePageEventOneOf2NodeAppStop
 */
export interface NodePageEventOneOf2NodeAppStop {
  /**
   *
   * @type {string}
   * @memberof NodePageEventOneOf2NodeAppStop
   */
  nodeId: string;
  /**
   *
   * @type {Date}
   * @memberof NodePageEventOneOf2NodeAppStop
   */
  stopDate: Date;
}

/**
 * Check if a given object implements the NodePageEventOneOf2NodeAppStop interface.
 */
export function instanceOfNodePageEventOneOf2NodeAppStop(value: object): value is NodePageEventOneOf2NodeAppStop {
  if (!('nodeId' in value) || value['nodeId'] === undefined) return false;
  if (!('stopDate' in value) || value['stopDate'] === undefined) return false;
  return true;
}

export function NodePageEventOneOf2NodeAppStopFromJSON(json: any): NodePageEventOneOf2NodeAppStop {
  return NodePageEventOneOf2NodeAppStopFromJSONTyped(json, false);
}

export function NodePageEventOneOf2NodeAppStopFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodePageEventOneOf2NodeAppStop {
  if (json == null) {
    return json;
  }
  return {

    'nodeId': json['node_id'],
    'stopDate': (new Date(json['stop_date'])),
  };
}

export function NodePageEventOneOf2NodeAppStopToJSON(json: any): NodePageEventOneOf2NodeAppStop {
  return NodePageEventOneOf2NodeAppStopToJSONTyped(json, false);
}

export function NodePageEventOneOf2NodeAppStopToJSONTyped(value?: NodePageEventOneOf2NodeAppStop | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'node_id': value['nodeId'],
    'stop_date': ((value['stopDate']).toISOString()),
  };
}

