/* tslint:disable */
/* eslint-disable */
/**
 * tracing-lv-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppNodeRunDto } from './AppNodeRunDto';
import {
    AppNodeRunDtoFromJSON,
    AppNodeRunDtoFromJSONTyped,
    AppNodeRunDtoToJSON,
    AppNodeRunDtoToJSONTyped,
} from './AppNodeRunDto';

/**
 * 
 * @export
 * @interface NodePageEventOneOf
 */
export interface NodePageEventOneOf {
    /**
     * 
     * @type {AppNodeRunDto}
     * @memberof NodePageEventOneOf
     */
    newNode: AppNodeRunDto;
}

/**
 * Check if a given object implements the NodePageEventOneOf interface.
 */
export function instanceOfNodePageEventOneOf(value: object): value is NodePageEventOneOf {
    if (!('newNode' in value) || value['newNode'] === undefined) return false;
    return true;
}

export function NodePageEventOneOfFromJSON(json: any): NodePageEventOneOf {
    return NodePageEventOneOfFromJSONTyped(json, false);
}

export function NodePageEventOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodePageEventOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        'newNode': AppNodeRunDtoFromJSON(json['NewNode']),
    };
}

  export function NodePageEventOneOfToJSON(json: any): NodePageEventOneOf {
      return NodePageEventOneOfToJSONTyped(json, false);
  }

  export function NodePageEventOneOfToJSONTyped(value?: NodePageEventOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'NewNode': AppNodeRunDtoToJSON(value['newNode']),
    };
}

