/* tslint:disable */
/* eslint-disable */
/**
 * tracing_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {mapValues} from '../runtime';
import type {AppLatestInfoDto} from './AppLatestInfoDto';
import {
  AppLatestInfoDtoFromJSON,
  AppLatestInfoDtoFromJSONTyped,
  AppLatestInfoDtoToJSON,
  AppLatestInfoDtoToJSONTyped,
} from './AppLatestInfoDto';

/**
 *
 * @export
 * @interface PageAppDto
 */
export interface PageAppDto {
  /**
   *
   * @type {AppLatestInfoDto}
   * @memberof PageAppDto
   */
  base: AppLatestInfoDto;
  /**
   *
   * @type {number}
   * @memberof PageAppDto
   */
  onlineNodeCount: number;
}

/**
 * Check if a given object implements the PageAppDto interface.
 */
export function instanceOfPageAppDto(value: object): value is PageAppDto {
  if (!('base' in value) || value['base'] === undefined) return false;
  if (!('onlineNodeCount' in value) || value['onlineNodeCount'] === undefined) return false;
  return true;
}

export function PageAppDtoFromJSON(json: any): PageAppDto {
  return PageAppDtoFromJSONTyped(json, false);
}

export function PageAppDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageAppDto {
  if (json == null) {
    return json;
  }
  return {

    'base': AppLatestInfoDtoFromJSON(json['base']),
    'onlineNodeCount': json['online_node_count'],
  };
}

export function PageAppDtoToJSON(json: any): PageAppDto {
  return PageAppDtoToJSONTyped(json, false);
}

export function PageAppDtoToJSONTyped(value?: PageAppDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'base': AppLatestInfoDtoToJSON(value['base']),
    'online_node_count': value['onlineNodeCount'],
  };
}

