/* tslint:disable */
/* eslint-disable */
/**
 * tracing_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppNodeRunDto } from './AppNodeRunDto';
import {
    AppNodeRunDtoFromJSON,
    AppNodeRunDtoFromJSONTyped,
    AppNodeRunDtoToJSON,
    AppNodeRunDtoToJSONTyped,
} from './AppNodeRunDto';

/**
 * 
 * @export
 * @interface PageNodeDto
 */
export interface PageNodeDto {
    /**
     * 
     * @type {AppNodeRunDto}
     * @memberof PageNodeDto
     */
    base: AppNodeRunDto;
}

/**
 * Check if a given object implements the PageNodeDto interface.
 */
export function instanceOfPageNodeDto(value: object): value is PageNodeDto {
    if (!('base' in value) || value['base'] === undefined) return false;
    return true;
}

export function PageNodeDtoFromJSON(json: any): PageNodeDto {
    return PageNodeDtoFromJSONTyped(json, false);
}

export function PageNodeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageNodeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'base': AppNodeRunDtoFromJSON(json['base']),
    };
}

  export function PageNodeDtoToJSON(json: any): PageNodeDto {
      return PageNodeDtoToJSONTyped(json, false);
  }

  export function PageNodeDtoToJSONTyped(value?: PageNodeDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'base': AppNodeRunDtoToJSON(value['base']),
    };
}

