/* tslint:disable */
/* eslint-disable */
/**
 * tracing_server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {mapValues} from '../runtime';
import type {AppNodeRunDto} from './AppNodeRunDto';
import {
  AppNodeRunDtoFromJSON,
  AppNodeRunDtoFromJSONTyped,
  AppNodeRunDtoToJSON,
  AppNodeRunDtoToJSONTyped,
} from './AppNodeRunDto';
import type {PageAppDto} from './PageAppDto';
import {
  PageAppDtoFromJSON,
  PageAppDtoFromJSONTyped,
  PageAppDtoToJSON,
  PageAppDtoToJSONTyped,
} from './PageAppDto';

/**
 *
 * @export
 * @interface PageDto
 */
export interface PageDto {
  /**
   *
   * @type {Array<PageAppDto>}
   * @memberof PageDto
   */
  apps: Array<PageAppDto>;
  /**
   *
   * @type {Date}
   * @memberof PageDto
   */
  date: Date;
  /**
   *
   * @type {Array<AppNodeRunDto>}
   * @memberof PageDto
   */
  nodes: Array<AppNodeRunDto>;
}

/**
 * Check if a given object implements the PageDto interface.
 */
export function instanceOfPageDto(value: object): value is PageDto {
  if (!('apps' in value) || value['apps'] === undefined) return false;
  if (!('date' in value) || value['date'] === undefined) return false;
  if (!('nodes' in value) || value['nodes'] === undefined) return false;
  return true;
}

export function PageDtoFromJSON(json: any): PageDto {
  return PageDtoFromJSONTyped(json, false);
}

export function PageDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PageDto {
  if (json == null) {
    return json;
  }
  return {

    'apps': ((json['apps'] as Array<any>).map(PageAppDtoFromJSON)),
    'date': (new Date(json['date'])),
    'nodes': ((json['nodes'] as Array<any>).map(AppNodeRunDtoFromJSON)),
  };
}

export function PageDtoToJSON(json: any): PageDto {
  return PageDtoToJSONTyped(json, false);
}

export function PageDtoToJSONTyped(value?: PageDto | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {

    'apps': ((value['apps'] as Array<any>).map(PageAppDtoToJSON)),
    'date': ((value['date']).toISOString()),
    'nodes': ((value['nodes'] as Array<any>).map(AppNodeRunDtoToJSON)),
  };
}

