/* tslint:disable */
/* eslint-disable */
/**
 * tracing-lv-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TLBinOp = {
    And: 'And',
    Or: 'Or',
    Like: 'Like',
    NotLike: 'NotLike',
    Is: 'Is',
    IsNot: 'IsNot',
    In: 'In',
    NotIn: 'NotIn',
    Between: 'Between',
    NotBetween: 'NotBetween',
    Equal: 'Equal',
    NotEqual: 'NotEqual',
    SmallerThan: 'SmallerThan',
    GreaterThan: 'GreaterThan',
    SmallerThanOrEqual: 'SmallerThanOrEqual',
    GreaterThanOrEqual: 'GreaterThanOrEqual'
} as const;
export type TLBinOp = typeof TLBinOp[keyof typeof TLBinOp];


export function instanceOfTLBinOp(value: any): boolean {
    for (const key in TLBinOp) {
        if (Object.prototype.hasOwnProperty.call(TLBinOp, key)) {
            if (TLBinOp[key as keyof typeof TLBinOp] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TLBinOpFromJSON(json: any): TLBinOp {
    return TLBinOpFromJSONTyped(json, false);
}

export function TLBinOpFromJSONTyped(json: any, ignoreDiscriminator: boolean): TLBinOp {
    return json as TLBinOp;
}

export function TLBinOpToJSON(value?: TLBinOp | null): any {
    return value as any;
}

export function TLBinOpToJSONTyped(value: any, ignoreDiscriminator: boolean): TLBinOp {
    return value as TLBinOp;
}

