/* tslint:disable */
/* eslint-disable */
/**
 * tracing-lv-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TracingSpanEnterDto
 */
export interface TracingSpanEnterDto {
    /**
     * 
     * @type {string}
     * @memberof TracingSpanEnterDto
     */
    alreadyRun?: string | null;
    /**
     * 
     * @type {number}
     * @memberof TracingSpanEnterDto
     */
    duration?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TracingSpanEnterDto
     */
    enterElapsed?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof TracingSpanEnterDto
     */
    enterTime: Date;
    /**
     * 
     * @type {string}
     * @memberof TracingSpanEnterDto
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof TracingSpanEnterDto
     */
    leaveRecordId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TracingSpanEnterDto
     */
    recordId: number;
    /**
     * 
     * @type {string}
     * @memberof TracingSpanEnterDto
     */
    spanRunId: string;
}

/**
 * Check if a given object implements the TracingSpanEnterDto interface.
 */
export function instanceOfTracingSpanEnterDto(value: object): value is TracingSpanEnterDto {
    if (!('enterTime' in value) || value['enterTime'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('recordId' in value) || value['recordId'] === undefined) return false;
    if (!('spanRunId' in value) || value['spanRunId'] === undefined) return false;
    return true;
}

export function TracingSpanEnterDtoFromJSON(json: any): TracingSpanEnterDto {
    return TracingSpanEnterDtoFromJSONTyped(json, false);
}

export function TracingSpanEnterDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TracingSpanEnterDto {
    if (json == null) {
        return json;
    }
    return {
        
        'alreadyRun': json['already_run'] == null ? undefined : json['already_run'],
        'duration': json['duration'] == null ? undefined : json['duration'],
        'enterElapsed': json['enter_elapsed'] == null ? undefined : json['enter_elapsed'],
        'enterTime': (new Date(json['enter_time'])),
        'id': json['id'],
        'leaveRecordId': json['leave_record_id'] == null ? undefined : json['leave_record_id'],
        'recordId': json['record_id'],
        'spanRunId': json['span_run_id'],
    };
}

  export function TracingSpanEnterDtoToJSON(json: any): TracingSpanEnterDto {
      return TracingSpanEnterDtoToJSONTyped(json, false);
  }

  export function TracingSpanEnterDtoToJSONTyped(value?: TracingSpanEnterDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'already_run': value['alreadyRun'],
        'duration': value['duration'],
        'enter_elapsed': value['enterElapsed'],
        'enter_time': ((value['enterTime']).toISOString()),
        'id': value['id'],
        'leave_record_id': value['leaveRecordId'],
        'record_id': value['recordId'],
        'span_run_id': value['spanRunId'],
    };
}

