/* tslint:disable */
/* eslint-disable */
/**
 * tracing-lv-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TracingRecordDto } from './TracingRecordDto';
import {
    TracingRecordDtoFromJSON,
    TracingRecordDtoFromJSONTyped,
    TracingRecordDtoToJSON,
    TracingRecordDtoToJSONTyped,
} from './TracingRecordDto';

/**
 * 
 * @export
 * @interface TracingSpanRunDto
 */
export interface TracingSpanRunDto {
    /**
     * 
     * @type {string}
     * @memberof TracingSpanRunDto
     */
    appRunId: string;
    /**
     * 
     * @type {number}
     * @memberof TracingSpanRunDto
     */
    busyDuration?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TracingSpanRunDto
     */
    closeRecordId?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof TracingSpanRunDto
     */
    exceptionEnd?: Date | null;
    /**
     * 
     * @type {object}
     * @memberof TracingSpanRunDto
     */
    fields: object;
    /**
     * 
     * @type {string}
     * @memberof TracingSpanRunDto
     */
    id: string;
    /**
     * 
     * @type {number}
     * @memberof TracingSpanRunDto
     */
    idleDuration?: number | null;
    /**
     * 
     * @type {number}
     * @memberof TracingSpanRunDto
     */
    recordId: number;
    /**
     * 
     * @type {Array<TracingRecordDto>}
     * @memberof TracingSpanRunDto
     */
    relatedEvents: Array<TracingRecordDto>;
    /**
     * 
     * @type {number}
     * @memberof TracingSpanRunDto
     */
    runElapsed?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof TracingSpanRunDto
     */
    runTime: Date;
    /**
     * 
     * @type {string}
     * @memberof TracingSpanRunDto
     */
    spanId: string;
}

/**
 * Check if a given object implements the TracingSpanRunDto interface.
 */
export function instanceOfTracingSpanRunDto(value: object): value is TracingSpanRunDto {
    if (!('appRunId' in value) || value['appRunId'] === undefined) return false;
    if (!('fields' in value) || value['fields'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('recordId' in value) || value['recordId'] === undefined) return false;
    if (!('relatedEvents' in value) || value['relatedEvents'] === undefined) return false;
    if (!('runTime' in value) || value['runTime'] === undefined) return false;
    if (!('spanId' in value) || value['spanId'] === undefined) return false;
    return true;
}

export function TracingSpanRunDtoFromJSON(json: any): TracingSpanRunDto {
    return TracingSpanRunDtoFromJSONTyped(json, false);
}

export function TracingSpanRunDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TracingSpanRunDto {
    if (json == null) {
        return json;
    }
    return {
        
        'appRunId': json['app_run_id'],
        'busyDuration': json['busy_duration'] == null ? undefined : json['busy_duration'],
        'closeRecordId': json['close_record_id'] == null ? undefined : json['close_record_id'],
        'exceptionEnd': json['exception_end'] == null ? undefined : (new Date(json['exception_end'])),
        'fields': json['fields'],
        'id': json['id'],
        'idleDuration': json['idle_duration'] == null ? undefined : json['idle_duration'],
        'recordId': json['record_id'],
        'relatedEvents': ((json['related_events'] as Array<any>).map(TracingRecordDtoFromJSON)),
        'runElapsed': json['run_elapsed'] == null ? undefined : json['run_elapsed'],
        'runTime': (new Date(json['run_time'])),
        'spanId': json['span_id'],
    };
}

  export function TracingSpanRunDtoToJSON(json: any): TracingSpanRunDto {
      return TracingSpanRunDtoToJSONTyped(json, false);
  }

  export function TracingSpanRunDtoToJSONTyped(value?: TracingSpanRunDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_run_id': value['appRunId'],
        'busy_duration': value['busyDuration'],
        'close_record_id': value['closeRecordId'],
        'exception_end': value['exceptionEnd'] == null ? undefined : ((value['exceptionEnd'] as any).toISOString()),
        'fields': value['fields'],
        'id': value['id'],
        'idle_duration': value['idleDuration'],
        'record_id': value['recordId'],
        'related_events': ((value['relatedEvents'] as Array<any>).map(TracingRecordDtoToJSON)),
        'run_elapsed': value['runElapsed'],
        'run_time': ((value['runTime']).toISOString()),
        'span_id': value['spanId'],
    };
}

