/* tslint:disable */
/* eslint-disable */
/**
 * tracing-lv-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TracingKind } from './TracingKind';
import {
    TracingKindFromJSON,
    TracingKindFromJSONTyped,
    TracingKindToJSON,
    TracingKindToJSONTyped,
} from './TracingKind';
import type { TracingLevel } from './TracingLevel';
import {
    TracingLevelFromJSON,
    TracingLevelFromJSONTyped,
    TracingLevelToJSON,
    TracingLevelToJSONTyped,
} from './TracingLevel';

/**
 * 
 * @export
 * @interface TracingRecordDto
 */
export interface TracingRecordDto {
    /**
     * 
     * @type {string}
     * @memberof TracingRecordDto
     */
    appId: string;
    /**
     * 
     * @type {string}
     * @memberof TracingRecordDto
     */
    appRunId: string;
    /**
     * 
     * @type {string}
     * @memberof TracingRecordDto
     */
    appVersion: string;
    /**
     * 
     * @type {Date}
     * @memberof TracingRecordDto
     */
    creationTime: Date;
    /**
     * 
     * @type {object}
     * @memberof TracingRecordDto
     */
    fields: object;
    /**
     * 
     * @type {number}
     * @memberof TracingRecordDto
     */
    id: number;
    /**
     * 
     * @type {TracingKind}
     * @memberof TracingRecordDto
     */
    kind: TracingKind;
    /**
     * 
     * @type {TracingLevel}
     * @memberof TracingRecordDto
     */
    level?: TracingLevel | null;
    /**
     * 
     * @type {string}
     * @memberof TracingRecordDto
     */
    modulePath?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TracingRecordDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof TracingRecordDto
     */
    nodeId: string;
    /**
     * 
     * @type {string}
     * @memberof TracingRecordDto
     */
    parentId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TracingRecordDto
     */
    parentSpanTId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TracingRecordDto
     */
    positionInfo?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof TracingRecordDto
     */
    recordTime: Date;
    /**
     * 
     * @type {number}
     * @memberof TracingRecordDto
     */
    repeatedCount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof TracingRecordDto
     */
    spanId?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TracingRecordDto
     */
    spanIdIsStable?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof TracingRecordDto
     */
    spanTId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof TracingRecordDto
     */
    target?: string | null;
}



/**
 * Check if a given object implements the TracingRecordDto interface.
 */
export function instanceOfTracingRecordDto(value: object): value is TracingRecordDto {
    if (!('appId' in value) || value['appId'] === undefined) return false;
    if (!('appRunId' in value) || value['appRunId'] === undefined) return false;
    if (!('appVersion' in value) || value['appVersion'] === undefined) return false;
    if (!('creationTime' in value) || value['creationTime'] === undefined) return false;
    if (!('fields' in value) || value['fields'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('kind' in value) || value['kind'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('nodeId' in value) || value['nodeId'] === undefined) return false;
    if (!('recordTime' in value) || value['recordTime'] === undefined) return false;
    return true;
}

export function TracingRecordDtoFromJSON(json: any): TracingRecordDto {
    return TracingRecordDtoFromJSONTyped(json, false);
}

export function TracingRecordDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TracingRecordDto {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'],
        'appRunId': json['app_run_id'],
        'appVersion': json['app_version'],
        'creationTime': (new Date(json['creation_time'])),
        'fields': json['fields'],
        'id': json['id'],
        'kind': TracingKindFromJSON(json['kind']),
        'level': json['level'] == null ? undefined : TracingLevelFromJSON(json['level']),
        'modulePath': json['module_path'] == null ? undefined : json['module_path'],
        'name': json['name'],
        'nodeId': json['node_id'],
        'parentId': json['parent_id'] == null ? undefined : json['parent_id'],
        'parentSpanTId': json['parent_span_t_id'] == null ? undefined : json['parent_span_t_id'],
        'positionInfo': json['position_info'] == null ? undefined : json['position_info'],
        'recordTime': (new Date(json['record_time'])),
        'repeatedCount': json['repeated_count'] == null ? undefined : json['repeated_count'],
        'spanId': json['span_id'] == null ? undefined : json['span_id'],
        'spanIdIsStable': json['span_id_is_stable'] == null ? undefined : json['span_id_is_stable'],
        'spanTId': json['span_t_id'] == null ? undefined : json['span_t_id'],
        'target': json['target'] == null ? undefined : json['target'],
    };
}

  export function TracingRecordDtoToJSON(json: any): TracingRecordDto {
      return TracingRecordDtoToJSONTyped(json, false);
  }

  export function TracingRecordDtoToJSONTyped(value?: TracingRecordDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'app_run_id': value['appRunId'],
        'app_version': value['appVersion'],
        'creation_time': ((value['creationTime']).toISOString()),
        'fields': value['fields'],
        'id': value['id'],
        'kind': TracingKindToJSON(value['kind']),
        'level': TracingLevelToJSON(value['level']),
        'module_path': value['modulePath'],
        'name': value['name'],
        'node_id': value['nodeId'],
        'parent_id': value['parentId'],
        'parent_span_t_id': value['parentSpanTId'],
        'position_info': value['positionInfo'],
        'record_time': ((value['recordTime']).toISOString()),
        'repeated_count': value['repeatedCount'],
        'span_id': value['spanId'],
        'span_id_is_stable': value['spanIdIsStable'],
        'span_t_id': value['spanTId'],
        'target': value['target'],
    };
}

