/* tslint:disable */
/* eslint-disable */
/**
 * tracing-lv-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TracingSpanEnterDto } from './TracingSpanEnterDto';
import {
    TracingSpanEnterDtoFromJSON,
    TracingSpanEnterDtoFromJSONTyped,
    TracingSpanEnterDtoToJSON,
    TracingSpanEnterDtoToJSONTyped,
} from './TracingSpanEnterDto';

/**
 * 
 * @export
 * @interface TracingTreeRecordVariantDtoOneOf1
 */
export interface TracingTreeRecordVariantDtoOneOf1 {
    /**
     * 
     * @type {TracingSpanEnterDto}
     * @memberof TracingTreeRecordVariantDtoOneOf1
     */
    spanEnter: TracingSpanEnterDto;
}

/**
 * Check if a given object implements the TracingTreeRecordVariantDtoOneOf1 interface.
 */
export function instanceOfTracingTreeRecordVariantDtoOneOf1(value: object): value is TracingTreeRecordVariantDtoOneOf1 {
    if (!('spanEnter' in value) || value['spanEnter'] === undefined) return false;
    return true;
}

export function TracingTreeRecordVariantDtoOneOf1FromJSON(json: any): TracingTreeRecordVariantDtoOneOf1 {
    return TracingTreeRecordVariantDtoOneOf1FromJSONTyped(json, false);
}

export function TracingTreeRecordVariantDtoOneOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): TracingTreeRecordVariantDtoOneOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'spanEnter': TracingSpanEnterDtoFromJSON(json['spanEnter']),
    };
}

  export function TracingTreeRecordVariantDtoOneOf1ToJSON(json: any): TracingTreeRecordVariantDtoOneOf1 {
      return TracingTreeRecordVariantDtoOneOf1ToJSONTyped(json, false);
  }

  export function TracingTreeRecordVariantDtoOneOf1ToJSONTyped(value?: TracingTreeRecordVariantDtoOneOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'spanEnter': TracingSpanEnterDtoToJSON(value['spanEnter']),
    };
}

