/* tslint:disable */
/* eslint-disable */
/**
 * tracing-lv-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AppRunDto } from './AppRunDto';
import {
    AppRunDtoFromJSON,
    AppRunDtoFromJSONTyped,
    AppRunDtoToJSON,
    AppRunDtoToJSONTyped,
} from './AppRunDto';

/**
 * 
 * @export
 * @interface TracingTreeRecordVariantDtoOneOf2
 */
export interface TracingTreeRecordVariantDtoOneOf2 {
    /**
     * 
     * @type {AppRunDto}
     * @memberof TracingTreeRecordVariantDtoOneOf2
     */
    appRun: AppRunDto;
}

/**
 * Check if a given object implements the TracingTreeRecordVariantDtoOneOf2 interface.
 */
export function instanceOfTracingTreeRecordVariantDtoOneOf2(value: object): value is TracingTreeRecordVariantDtoOneOf2 {
    if (!('appRun' in value) || value['appRun'] === undefined) return false;
    return true;
}

export function TracingTreeRecordVariantDtoOneOf2FromJSON(json: any): TracingTreeRecordVariantDtoOneOf2 {
    return TracingTreeRecordVariantDtoOneOf2FromJSONTyped(json, false);
}

export function TracingTreeRecordVariantDtoOneOf2FromJSONTyped(json: any, ignoreDiscriminator: boolean): TracingTreeRecordVariantDtoOneOf2 {
    if (json == null) {
        return json;
    }
    return {
        
        'appRun': AppRunDtoFromJSON(json['appRun']),
    };
}

  export function TracingTreeRecordVariantDtoOneOf2ToJSON(json: any): TracingTreeRecordVariantDtoOneOf2 {
      return TracingTreeRecordVariantDtoOneOf2ToJSONTyped(json, false);
  }

  export function TracingTreeRecordVariantDtoOneOf2ToJSONTyped(value?: TracingTreeRecordVariantDtoOneOf2 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'appRun': AppRunDtoToJSON(value['appRun']),
    };
}

