/* tslint:disable */
/* eslint-disable */
/**
 * tracing-lv-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TracingTreeRecordVariantDtoOneOf } from './TracingTreeRecordVariantDtoOneOf';
import {
    instanceOfTracingTreeRecordVariantDtoOneOf,
    TracingTreeRecordVariantDtoOneOfFromJSON,
    TracingTreeRecordVariantDtoOneOfFromJSONTyped,
    TracingTreeRecordVariantDtoOneOfToJSON,
} from './TracingTreeRecordVariantDtoOneOf';
import type { TracingTreeRecordVariantDtoOneOf1 } from './TracingTreeRecordVariantDtoOneOf1';
import {
    instanceOfTracingTreeRecordVariantDtoOneOf1,
    TracingTreeRecordVariantDtoOneOf1FromJSON,
    TracingTreeRecordVariantDtoOneOf1FromJSONTyped,
    TracingTreeRecordVariantDtoOneOf1ToJSON,
} from './TracingTreeRecordVariantDtoOneOf1';
import type { TracingTreeRecordVariantDtoOneOf2 } from './TracingTreeRecordVariantDtoOneOf2';
import {
    instanceOfTracingTreeRecordVariantDtoOneOf2,
    TracingTreeRecordVariantDtoOneOf2FromJSON,
    TracingTreeRecordVariantDtoOneOf2FromJSONTyped,
    TracingTreeRecordVariantDtoOneOf2ToJSON,
} from './TracingTreeRecordVariantDtoOneOf2';

/**
 * @type TracingTreeRecordVariantDto
 * 
 * @export
 */
export type TracingTreeRecordVariantDto = TracingTreeRecordVariantDtoOneOf | TracingTreeRecordVariantDtoOneOf1 | TracingTreeRecordVariantDtoOneOf2;

export function TracingTreeRecordVariantDtoFromJSON(json: any): TracingTreeRecordVariantDto {
    return TracingTreeRecordVariantDtoFromJSONTyped(json, false);
}

export function TracingTreeRecordVariantDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TracingTreeRecordVariantDto {
    if (json == null) {
        return json;
    }
    if (instanceOfTracingTreeRecordVariantDtoOneOf(json)) {
        return TracingTreeRecordVariantDtoOneOfFromJSONTyped(json, true);
    }
    if (instanceOfTracingTreeRecordVariantDtoOneOf1(json)) {
        return TracingTreeRecordVariantDtoOneOf1FromJSONTyped(json, true);
    }
    if (instanceOfTracingTreeRecordVariantDtoOneOf2(json)) {
        return TracingTreeRecordVariantDtoOneOf2FromJSONTyped(json, true);
    }

    return {} as any;
}

export function TracingTreeRecordVariantDtoToJSON(value?: TracingTreeRecordVariantDto | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfTracingTreeRecordVariantDtoOneOf(value)) {
        return TracingTreeRecordVariantDtoOneOfToJSON(value as TracingTreeRecordVariantDtoOneOf);
    }
    if (instanceOfTracingTreeRecordVariantDtoOneOf1(value)) {
        return TracingTreeRecordVariantDtoOneOf1ToJSON(value as TracingTreeRecordVariantDtoOneOf1);
    }
    if (instanceOfTracingTreeRecordVariantDtoOneOf2(value)) {
        return TracingTreeRecordVariantDtoOneOf2ToJSON(value as TracingTreeRecordVariantDtoOneOf2);
    }

    return {};
}

