/* tslint:disable */
/* eslint-disable */
/**
 * tracing-lv-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const TracingKind = {
    SpanCreate: 'SpanCreate',
    SpanEnter: 'SpanEnter',
    SpanLeave: 'SpanLeave',
    SpanClose: 'SpanClose',
    SpanRecord: 'SpanRecord',
    Event: 'Event',
    RepEvent: 'RepEvent',
    AppStart: 'AppStart',
    AppStop: 'AppStop',
    DataUpdate: 'DataUpdate',
    RelatedEvent: 'RelatedEvent'
} as const;
export type TracingKind = typeof TracingKind[keyof typeof TracingKind];


export function instanceOfTracingKind(value: any): boolean {
    for (const key in TracingKind) {
        if (Object.prototype.hasOwnProperty.call(TracingKind, key)) {
            if (TracingKind[key as keyof typeof TracingKind] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TracingKindFromJSON(json: any): TracingKind {
    return TracingKindFromJSONTyped(json, false);
}

export function TracingKindFromJSONTyped(json: any, ignoreDiscriminator: boolean): TracingKind {
    return json as TracingKind;
}

export function TracingKindToJSON(value?: TracingKind | null): any {
    return value as any;
}

export function TracingKindToJSONTyped(value: any, ignoreDiscriminator: boolean): TracingKind {
    return value as TracingKind;
}

