/* tslint:disable */
/* eslint-disable */
/**
 * tracing-lv-server
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TracingTreeEndDto
 */
export interface TracingTreeEndDto {
    /**
     * 
     * @type {Date}
     * @memberof TracingTreeEndDto
     */
    endDate: Date;
    /**
     * 
     * @type {Date}
     * @memberof TracingTreeEndDto
     */
    exceptionEnd?: Date | null;
    /**
     * 
     * @type {number}
     * @memberof TracingTreeEndDto
     */
    runElapsed?: number | null;
}

/**
 * Check if a given object implements the TracingTreeEndDto interface.
 */
export function instanceOfTracingTreeEndDto(value: object): value is TracingTreeEndDto {
    if (!('endDate' in value) || value['endDate'] === undefined) return false;
    return true;
}

export function TracingTreeEndDtoFromJSON(json: any): TracingTreeEndDto {
    return TracingTreeEndDtoFromJSONTyped(json, false);
}

export function TracingTreeEndDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TracingTreeEndDto {
    if (json == null) {
        return json;
    }
    return {
        
        'endDate': (new Date(json['end_date'])),
        'exceptionEnd': json['exception_end'] == null ? undefined : (new Date(json['exception_end'])),
        'runElapsed': json['run_elapsed'] == null ? undefined : json['run_elapsed'],
    };
}

  export function TracingTreeEndDtoToJSON(json: any): TracingTreeEndDto {
      return TracingTreeEndDtoToJSONTyped(json, false);
  }

  export function TracingTreeEndDtoToJSONTyped(value?: TracingTreeEndDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'end_date': ((value['endDate']).toISOString()),
        'exception_end': value['exceptionEnd'] == null ? undefined : ((value['exceptionEnd'] as any).toISOString()),
        'run_elapsed': value['runElapsed'],
    };
}

