/* @ts-nocheck */
/* eslint-disable */
/* @noformat */
/* @formatter:off */
/**
* Generated by ng-openapi
* Generated TypeScript interfaces from Swagger specification
* Do not edit this file manually
*/
import { HttpContext, HttpHeaders } from "@angular/common/http";
export interface AppLatestInfoDto {
    build_time: Date;
    id: string;
    name: string;
    node_count: number;
    online_node_count: number;
}

export interface AppNodeRunDto {
    app_build_ids: Array<Array<unknown>>;
    app_run_id: string;
    creation_time: Date;
    data: Record<string, unknown>;
    exception_end: boolean;
    node_id: string;
    record_id: number;
    start_time: Date;
    stop_record_id?: number | null;
    stop_time?: string | null;
}

export interface AppRunDto {
    app_id: string;
    app_version: string;
    creation_time: Date;
    data: Record<string, unknown>;
    exception_end: boolean;
    id: string;
    record_id: number;
    run_elapsed?: number | null;
    start_time: Date;
    stop_record_id?: number | null;
    stop_time?: string | null;
}

export interface CursorInfo {
    id: number;
    is_before: boolean;
}

export type NodePageEvent = { NewNode: AppNodeRunDto } | { NodeAppStart: AppNodeRunDto } | { NodeAppStop: AppNodeRunDto };

export interface NodesPageDto {
    apps: Array<AppLatestInfoDto>;
    date: Date;
    nodes: Array<AppNodeRunDto>;
}

export enum TLBinOp {
    And = "And",
    Or = "Or",
    Like = "Like",
    NotLike = "NotLike",
    Is = "Is",
    IsNot = "IsNot",
    In = "In",
    NotIn = "NotIn",
    Between = "Between",
    NotBetween = "NotBetween",
    Equal = "Equal",
    NotEqual = "NotEqual",
    SmallerThan = "SmallerThan",
    GreaterThan = "GreaterThan",
    SmallerThanOrEqual = "SmallerThanOrEqual",
    GreaterThanOrEqual = "GreaterThanOrEqual"
}

export enum TracingKind {
    SpanCreate = "SpanCreate",
    SpanEnter = "SpanEnter",
    SpanLeave = "SpanLeave",
    SpanClose = "SpanClose",
    SpanRecord = "SpanRecord",
    Event = "Event",
    RepEvent = "RepEvent",
    AppStart = "AppStart",
    AppStop = "AppStop",
    DataUpdate = "DataUpdate",
    RelatedEvent = "RelatedEvent"
}

export enum TracingLevel {
    Trace = "Trace",
    Debug = "Debug",
    Info = "Info",
    Warn = "Warn",
    Error = "Error"
}

export interface TracingRecordDto {
    app_id: string;
    app_run_id: string;
    app_version: string;
    creation_time: Date;
    fields: Record<string, unknown>;
    id: number;
    kind: TracingKind;
    level?: null | TracingLevel;
    module_path?: string | null;
    name: string;
    node_id: string;
    parent_id?: string | null;
    parent_span_t_id?: string | null;
    position_info?: string | null;
    record_index: number;
    record_time: Date;
    repeated_count?: number | null;
    span_id?: string | null;
    span_id_is_stable?: boolean | null;
    span_t_id?: string | null;
    target?: string | null;
}

export interface TracingRecordFieldFilter {
    name: string;
    op: TLBinOp;
    value?: string | null;
}

export enum TracingRecordScene {
    Tree = "Tree",
    SpanField = "SpanField",
    SpanEnter = "SpanEnter"
}

export interface TracingSpanEnterDto {
    already_run?: string | null;
    duration?: number | null;
    enter_elapsed?: number | null;
    enter_time: Date;
    id: string;
    leave_record_id?: number | null;
    record_id: number;
    span_run_id: string;
}

export interface TracingSpanRunDto {
    app_run_id: string;
    busy_duration?: number | null;
    close_record_id?: number | null;
    exception_end?: string | null;
    fields: Record<string, unknown>;
    id: string;
    idle_duration?: number | null;
    record_id: number;
    related_events: Array<TracingRecordDto>;
    run_elapsed?: number | null;
    run_time: Date;
    span_id: string;
}

export interface TracingTreeEndDto {
    end_date: Date;
    exception_end?: string | null;
}

export interface TracingTreeRecordDto {
    end?: null | TracingTreeEndDto;
    record: TracingRecordDto;
    variant?: null | TracingTreeRecordVariantDto;
}

export type TracingTreeRecordVariantDto = { spanRun: TracingSpanRunDto } | { spanEnter: TracingSpanEnterDto } | { appRun: AppRunDto };

/** Request Options for Angular HttpClient requests */
export interface RequestOptions<TResponseType extends 'arraybuffer' | 'blob' | 'json' | 'text'> {
    headers?: HttpHeaders;
    reportProgress?: boolean;
    responseType?: TResponseType;
    withCredentials?: boolean;
    context?: HttpContext;
}
